# Generated by Django 3.2 on 2021-05-02 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_published']},
        ),
        migrations.AddField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
