# Generated by Django 3.2 on 2021-05-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0002_auto_20210502_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_published']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='intro',
        ),
    ]
