# Generated by Django 3.2 on 2021-05-03 21:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0004_postcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
