# Generated by Django 3.2 on 2021-05-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0005_auto_20210503_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
