# Generated by Django 3.2 on 2021-05-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0006_postcomments_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
