# Generated by Django 3.2 on 2021-05-04 13:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0011_auto_20210504_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=150)),
                ('review', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paulinsblog.post')),
            ],
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
