# Generated by Django 3.2 on 2021-05-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paulinsblog', '0012_auto_20210504_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
